// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/apids-layout/HubDock.tsx": () => import("../components/mockups/apids-layout/HubDock.tsx"),
  "./components/mockups/apids-layout/SplitPane.tsx": () => import("../components/mockups/apids-layout/SplitPane.tsx"),
  "./components/mockups/apids-layout/TopNav.tsx": () => import("../components/mockups/apids-layout/TopNav.tsx")
};
